apiControllersMeeting:
    resource: ../src/Meeting/Application/Controller
    type: attribute
    prefix: /api

webControllersMeeting:
    resource: ../src/Shared/Application/Controller
    type: attribute